### ISSUE TITLE
Memory mapping configurable?

### ISSUE THREAD

**Issue by edwardcwang** [pretis/flexpret#3]
@mzimmer Are the instruction and data memories always mapped to 0x0? From a quick reading of the code it seems like it's hardcoded (e.g. `io.dmem.addr := io.addr(conf.dMemAddrBits-1, 2)`), but just wanted to check - e.g. in case we want to map `dmem` to `0x8000_0000` or something.

**Comment by mzimmer** [comment]
It looks like they are mapped to different addresses, so even though the address is passed through, the enable signal won't be active if it's intended for a different memory. `tests/test.mk` defines `TEXT_START_ADDR=0x00000000` and `DATA_START_ADDR=0x20000000` for compiling the executable, and the chisel code in `src/Core/constants.scala` defines `ADDR_ISPM_VAL` and `ADDR_DSPM_VAL`, which are used in `src/Core/loadstore.scala` to set `dmem_op` and `imem_op`.
