### ISSUE TITLE
riscv64-unknown-elf-gcc: error: unrecognized command line option '-m32'

### ISSUE THREAD

**Issue by nuaaysh** [pretis/flexpret#4]
flexpretnuaa@flexpretnuaa:~/flexpret-riscv-2.0$ make run
mkdir -p tests/isa/build/emulator
riscv64-unknown-elf-gcc -m32 -Itests/include -c tests/isa/add.S -o tests/isa/build/emulator/add.o
riscv64-unknown-elf-gcc: error: unrecognized command line option '-m32'
make: *** [tests/isa/build/emulator/add.o] error 1

It looks like the riscv64-unknown-elf-gcc has not supported the flag '-m32'， Could you give some suggestions?
The version of my riscv64-unknown-elf-gcc is 8.2.0

**Comment by edwardcwang** [comment]
I think you have to use the specific git revision outlined in the README: https://github.com/pretis/flexpret/blob/9c2fe4ea286e24767d7a76bec0412877161873b1/README.md#risc-v-compiler

**Comment by nuaaysh** [comment]
I try to use the specific revision but  it also does not work.
The author of RISCV told me the order version may not be useful. Please check 'https://github.com/riscv/riscv-gnu-toolchain/issues/357'

I also try to ask my friends for help to build Flexpret in Docker. but something is wrong. Please check ‘ Build Docker Failed #5‘.

What should I do? Do you have a stable version of Flexpret? Maybe a virtual machine file or something else. ^_^

**Comment by mzimmer** [comment]
The makefiles and processor itself have not been updated yet for the changes in the RISC-V compiler over the past few years, so only an older revision will work.  The master branch is also under development, which is the cause of docker build problems in #5 . You should try checking out the 'riscv-2.0' branch and running `docker build .` in the `docker` directory. I'll also start it locally to make sure it works.

**Comment by lsk567** [comment]
This problem should be resolved if you follow the latest instructions here: https://github.com/pretis/flexpret#risc-v-compiler.
