### ISSUE TITLE
protected branch

### ISSUE THREAD

**Issue by schoeberl** [pretis/flexpret#40]
Thanks for adding me to the repo. However, I am not able to push a commit to it:

Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "pretis.flexpret" is expected.
To github.com:pretis/flexpret.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:pretis/flexpret.git'

Cheers,
Martin

**Comment by lsk567** [comment]
Hi @schoeberl, I think the master branch is protected and cannot be pushed to directly. Can you try pushing to a feature branch?
