### ISSUE TITLE
Build Docker Failed

### ISSUE THREAD

**Issue by magichan** [pretis/flexpret#5]
I build Dockerfile in /docker/Dockerfile for specific compiler version,
```
 docker build -t flexpret .
```
when the docker run the following command, I get some error. 
```sh
RUN curl -LO https://github.com/pretis/flexpret/archive/master.zip \
 && unzip master.zip \
 && rm master.zip \
 && cd flexpret-master \
 && echo $PATH \
 && make run
```
The error info:
```
[info] Running Core.CoreMain 4tf-16i-16d-ti --backend c --targetDir ../emulator/generated-src/4tf-16i-16d-ti --debug --vcd
features: ti
Error: Unknown option --backend
Error: Unknown option --targetDir
Error: Unknown option --debug
Error: Unknown option --vcd
Try --help for more information.
[success] Total time: 461 s, completed Sep 2, 2018 6:18:55 AM
make: *** No rule to make target 'emulator/generated-src/4tf-16i-16d-ti/Core.h', needed by 'emulator/build/4tf-16i-16d-ti/Core.o'.  Stop.
rm tests/isa/build/emulator/add.data tests/isa/build/emulator/add.inst
The command '/bin/sh -c curl -LO https://github.com/pretis/flexpret/archive/master.zip  && unzip master.zip  && rm master.zip  && cd flexpret-master  && echo $PATH  && make run' returned a non-zero code: 2
```

or 

![image](https://user-images.githubusercontent.com/9430353/44954029-39717400-aecf-11e8-9ee8-87f19bfee4e3.png)

Would you give me a hand to solve this problem. Thank you very much.

Environment:
```
Docker version 17.12.1-ce, build 7390fc6
```

**Comment by edwardcwang** [comment]
The master is currently under development (porting to Chisel3) and some interfaces were changed so the Dockerfile doesn't work out of the box, I think. Try with revision 446635af19f2ba54444da54afa49cba1a1c6d28d (probably need to modify the dockerfile to do so).

**Comment by mzimmer** [comment]
At the end of the Dockerfile it's cloning the repository and calling `make run`, but this will ignore any local branch or revision and just grab the latest master branch. I just fixed this on the 'riscv-2.0' branch to at least match branches. This last step is also completely unnecessary and can be removed (it's only in there to make sure everything worked without additional manual steps).

**Comment by edwardcwang** [comment]
The main Chisel3 port is complete but unfortunately the testers model changed so I'm still trying to figure out how to port the testers.

**Comment by erlingrj** [comment]
Closed because it seems out-of-date
