### ISSUE TITLE
`_fp_print()` does not print anymore after adding flexible scheduling support in the threading library

### ISSUE THREAD

**Issue by ChadliaJerad** [pretis/flexpret#52]
Running emulation of `add.c` program under `programs/tests/mt-c-tests/add` does not output anything to host, after the latest commit [Finish Chisel3 port and support flexible scheduling](https://github.com/pretis/flexpret/pull/50).

**Comment by lsk567** [comment]
This is not a problem on my end for some reason.
Can you show me how to reproduce it?

**Comment by ChadliaJerad** [comment]
This is weird!
I am on master, built the emulator with 3 hardware threads: ```make emulator THREADS=3```
and run: ``` riscv-compile.sh 3 add add.c``` 
But ```fp-emu +ispm=add.mem``` does not output anything...

**Comment by ChadliaJerad** [comment]
Found why!
It was because FLEXPRET was set to false... When set to true, it works perfectly...
So, the updated library does not support disabled SRTT. Right? Should be solved, right?

**Comment by lsk567** [comment]
Yes, sounds like there is a bug there. I will look into it.
This is also relevant to #53.

**Comment by erlingrj** [comment]
This particular issue is solved. So closing
