### ISSUE TITLE
Improved software compilation flow

### ISSUE THREAD

**Issue by erlingrj** [pretis/flexpret#55]
As we add more libraries and especially the software defined SoC devices which I have started to call `IP Devices` we need an efficient way of compiling and linking with a user-configurable number of libraries. I am envisioning having the `IP Devices` as separate Github repositories under the `pretis` organization and using either GNU Make or CMake to easily include them in your project.

I am curios why shell scripts are used instead of build tools like GNU Make and CMake, is this a historical reason or just preferences?

**Comment by lsk567** [comment]
Shell scripts are an ad-hoc solution when the C programs are small. It makes sense to switch to GNU Make or CMake.

**Comment by erlingrj** [comment]
Also I think we should make a core flexpret library which includes all CPU specific functionalities:
locks, threads, time, IO, asserts, CSRs ettc. Compiled into a single library that can be linked with apps. Then we can have separate libraries for the software defined devices
