### ISSUE TITLE
Compile  application

### ISSUE THREAD

**Issue by Med-Taher** [pretis/flexpret#7]
when i try to rebuild the files (complex-mc.data.mem; complex-mc.dump;complex-mc.inst.mem) which you can find in the directory flexpret-RTAS14/tests/complex-mc/build/emulator. 
/flexpret-RTAS14$ make run
make: *** No rule to make target 'tests/complex-mc/build/emulator/complex-mc.inst.mem', needed by 'tests/complex-mc/results/emulator/8tf-128i-128d-2smul-stats-exc-gt-du-ee/complex-mc.out'.  Stop.
it looks like those files were never built by the compiler (riscv-gcc).
If i need to execute another application what do I have  to do. Could you give some suggestions?

**Comment by mzimmer** [comment]
If I remember correctly, the compiled files for some tests are committed so that installing the right compiler version isn't required to run them, but if you want to rebuild you'll need to uncomment `#include $(TESTS_DIR)/tests.mk` from `Makefile` (or checkout the files again if deleted at some point)
https://github.com/pretis/flexpret/tree/RTAS14#risc-v-compiler

Let me know if that doesn't work.

**Comment by Med-Taher** [comment]
When i uncomment  #include $(TESTS_DIR)/tests.mk from Makefile. I have this problem which is related to the version of the compiler. and as they say (The latest version is not currently supported) and i cannot find this version   4806a4a74e82fd393ce8b9f3ea49d7675204d090 of riscv-tools.

/flexpret-RTAS14$ make run
mkdir -p tests/complex-mc/build/emulator
riscv-gcc -m32 -Itests/include -DSCHEDULE=0x53425140 -DTMODES=0x0000A000 -c tests/complex-mc/init.S -o tests/complex-mc/build/emulator/init.o
make: riscv-gcc: Command not found
tests/complex-mc/test.mk:24: recipe for target 'tests/complex-mc/build/emulator/init.o' failed
make: *** [tests/complex-mc/build/emulator/init.o] Error 127

Thank you so much.

**Comment by mzimmer** [comment]
This should be the link to that version of the compiler tools: https://github.com/riscv/riscv-tools/tree/4806a4a74e82fd393ce8b9f3ea49d7675204d090
